#! /usr/bin/python
import sys
import os
from subprocess import call
def main():
    """
    open -a Sublime\ Text file
    """
    if len(sys.argv) < 2:
        print 'Usage: %s FILE' % sys.argv[0]
        return
    call(['open', '-a', 'Sublime Text', sys.argv[1]])

if __name__ == '__main__':
    main()
