#! /usr/bin/python
import sys
import os
from subprocess import call
def main():
    """
    cd $REPO
    open TAG/TAG.txt
    """
    if len(sys.argv) < 2:
        print 'Usage: %s TAG' % sys.argv[0]
        return
    repo = os.environ['REPO']
    path = '%s/%s' % (repo, sys.argv[1])
    file = '%s/%s.txt' % (path, sys.argv[1])
    call(['open', file])

if __name__ == '__main__':
    main()