#! /usr/bin/python
import subprocess
def main():
    """
    pwd | pbcopy
    """
    p1 = subprocess.Popen(['pwd'], stdout=subprocess.PIPE)
    p2 = subprocess.Popen(['pbcopy'], stdin=p1.stdout)
    p1.stdout.close()

if __name__ == '__main__':
    main()
